summary 1
melvinsz/team_project pull request #15
Opened 2023-04-10 12:11 UTC by TetianaAsadova

render queue

2023-04-11 07:12 UTC, melvinsz requested changes

2023-04-11 07:12 UTC, melvinsz commented on src/addqueue.html
Вам не потрібно створювати html файл, Queue вже ж є в хедері, який зробила Анастасія, до тієї кнопки ви просто прив'зякуєте свій js

2023-04-11 07:12 UTC, melvinsz commented on src/addqueue.js
> +import './sass/_addqueue.scss';
навіщо імпортувати файл стилів в js?

2023-04-11 07:12 UTC, melvinsz commented on src/addqueue.js
> +        renderMovies(movies.);
movies. тут потрібна крапка?

2023-04-11 07:12 UTC, melvinsz commented on src/addqueue.js
> +        // Notiflix.Notify.info("");
Якщо будете використовувати Notiflix то дайте знати, щоб встановити його, можете мені написати

2023-04-11 07:12 UTC, melvinsz commented on package.json
чому тут пустий файл?

2023-04-11 07:12 UTC, melvinsz commented on src/index.html
чому тут пустий файл?

2023-04-11 07:12 UTC, melvinsz commented on src/sass/index.scss
чому тут пустий файл?

2023-04-11 07:12 UTC, melvinsz commented on src/addqueue.js
цей свій js маєте підключити в index.js

2023-04-11 07:12 UTC, melvinsz commented on src/sass/_addqueue.scss
цей свій scss маєте підключити в index.scss

2023-04-11 08:26 UTC, TetianaAsadova commented on src/addqueue.html
добре

2023-04-11 08:28 UTC, TetianaAsadova commented on src/addqueue.js
> +import './sass/_addqueue.scss';
це мені треба було, коли я намагалася працювати самостійно, видалю

2023-04-11 08:29 UTC, TetianaAsadova commented on src/addqueue.js
> +        renderMovies(movies.);
я збиралась підключити ту частину даних, де масив з фільмами, зараз все по-іншому

2023-04-11 08:32 UTC, TetianaAsadova commented on src/addqueue.js
> +        // Notiflix.Notify.info("");
ок, а за допомогою чого всі виводять повідомлення типу "Такий фільм вже є в черзі"?

2023-04-11 08:46 UTC, TetianaAsadova commented on src/addqueue.js
підключила

2023-04-11 08:49 UTC, TetianaAsadova commented on src/sass/index.scss
не зрозуміла ці три останні питання, що зовсім пусті, у мене вони заповнені, скидаю фото в лічку

2023-04-11 09:00 UTC, TetianaAsadova commented on src/sass/_addqueue.scss
підключила

2023-04-12 09:21 UTC, melvinsz approved these changes

2023-04-12 09:21 UTC, merged