add pagination.html and pagination.css
melvinsz/team_project pull request #3
Opened 2023-04-08 18:52 UTC by nikkuts

2023-04-08 19:43 UTC, melvinsz requested changes

2023-04-08 19:43 UTC, melvinsz commented on src/css/pagination.css
> +    font-family: 'Roboto';
подивіться там в файлі scss є дефолтне значення для боді, де то повторюється щоб не задавати знову і так з подібними, там кольори прогляньте

2023-04-08 19:43 UTC, melvinsz commented on src/partials/pagination.html
> +<ul class="btn-pagination">
а пагінація не реалізовується якось через js? чи то потім з'явиться?

2023-04-08 19:53 UTC, nikkuts commented on src/partials/pagination.html
> +<ul class="btn-pagination">
так, будемо перемальовувати при кожному запиті. а на початку потрібні кнопки, щоб повісити на них слухачів.

2023-04-08 21:36 UTC, nikkuts commented on src/css/pagination.css
> +    font-family: 'Roboto';
виправив

2023-04-09 07:09 UTC, melvinsz approved these changes

2023-04-09 07:09 UTC, merged